import argparse, pathlib

PROFILES = {
    "BM":  {"group":"BM", "display":"Bandwidth Miner", "metric":"Bandwidth speed", "unit":"Mbps"},
    "IDM": {"group":"Decibel",   "display":"Indoor Decibel Miner",  "metric":"Decibel","unit":"dBFS"},
    "ODM": {"group":"Decibel",   "display":"Outdoor Decibel Miner", "metric":"Decibel","unit":"dBFS"},
    # Node roles only track online status by hour; no live metrics
    "SVN": {"group":"SVN",       "display":"Storage Validator Node",        "metric":"Online status",    "unit":""},
    "SDN": {"group":"SDN",       "display":"Storage Decentralization Node", "metric":"Online status",    "unit":""},
    "RDN": {"group":"RDN",       "display":"Rewards Decentralization Node", "metric":"Online status",    "unit":""},
    "IRM": {"group":"Radiation", "display":"Radiation Miner",               "metric":"Radiation level",  "unit":"CPM"},
    "AEM": {"group":"AEM",       "display":"AEM Miner",             "metric":"Proof of Installed", "unit":""},
    "ISM": {"group":"Satellite", "display":"Indoor Satellite Miner","metric":"GNSS stream", "unit":""},
    "OSM": {"group":"Satellite", "display":"Outdoor Satellite Miner","metric":"GNSS stream", "unit":""},
}

TEMPLATE = """# AUTOGENERATED. DO NOT EDIT.
MINER_CODE = "{code}"
VERSION = "{version}"
GROUP = "{group}"
DISPLAY_NAME = "{display}"
METRIC_LABEL = "{metric}"
METRIC_UNIT = "{unit}"
DEV = False
VERSION_CHECK_SEC = {ver_check}
"""

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--code", required=True, choices=PROFILES.keys())
    ap.add_argument("--version", required=True)
    ap.add_argument("--out", default="config_profile.py")
    ap.add_argument("--version-check-sec", type=int, default=600)
    args = ap.parse_args()
    p = PROFILES[args.code]
    out = TEMPLATE.format(code=args.code, version=args.version, ver_check=max(1, int(args.version_check_sec)), **p)
    pathlib.Path(args.out).write_text(out, encoding="utf-8")
    print(f"Wrote {args.out} for {args.code} v{args.version}")

if __name__ == "__main__":
    main()
